### ISSUE TITLE
[Bug]: Number field broken since 3.13.0 - $tc is not a function

### ISSUE THREAD

**Issue by poacher2k** [shopware/meteor#453]
### Package

@meteor/component-library

### Package version

^3.13.0

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-bnlbnnhr?file=src%2FApp.vue

### Steps to reproduce

1. Use `mt-number-field`

### Actual behavior

An error occurs

### Expected behavior

It should work without an error

### System Info

```shell

```

### Any additional comments?

Likely caused by this line: https://github.com/shopware/meteor/commit/3ddcd2682bd7cca7556532cad38cdd8216352e2e#diff-8b997c46fb1e29550a38c10a142ec996c5df0cfca1caed44c84b8f82df497ddeR49

In our environment we have no `$tc` defined globally.

### Code of Conduct

- [x] I have read and agree to follow Meteor's [Code of Conduct](https://github.com/shopware/meteor/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haberkamp** [comment]
Hi, could it be that your app does not use `vue-i18n`? You can't use Meteor without using `vue-i18n` version 9. I could fix it by installing it, creating it like this:



```ts
const i18n = createI18n({
  locale: 'en'
});
```

and then using it like this:

```ts
app.use(i18n)
```

**Comment by poacher2k** [comment]
> Hi, could it be that your app does not use `vue-i18n`? You can't use Meteor without using `vue-i18n` version 9. I could fix it by installing it, creating it like this:

Our app does indeed use `vue-i18n`, and works fine with `3.12.0`. The update linked above in `3.13.0` broke our app as the `$tc` function is not defined, and this is likely the same for others too. Perhaps this wasn't noticed because of https://github.com/shopware/meteor/blob/43aab7a24dd7f6ae548d0d431d62a5fc6227c30b/examples/admin-sdk-plugin/src/Resources/app/administration/src/viewRenderer.ts#L51 ?

**Comment by Haberkamp** [comment]
Is it possible for you to send me a more detailed `vue-i18n` configuration? Once I add the basic `vue-i18n` to the minimal reproducable instance you sent me everything works as expected. The error is gone.

**Comment by poacher2k** [comment]
> Is it possible for you to send me a more detailed `vue-i18n` configuration? Once I add the basic `vue-i18n` configuration to the minimal reproducable instance you sent me everything works as expected. The error is gone.

Here is one with `vue-i18n`: https://stackblitz.com/edit/vitejs-vite-bnlbnnhr?file=package.json

**Comment by Haberkamp** [comment]
Ok, so the issues happens because `vue-i18n` is configured to not use the `legacy` mode. 

A few ways to fix this bug:
1. Enable the `legacy` mode and migrate all transitions over to the Options API
2. Upgrade Meteor to `4.0.0` where all translations use the Composition API
3. Use this [hack](https://github.com/shopware/meteor/pull/455)

The reason this bug appears is because Meteor 3 still uses the Options API to do translations and `vue-i18n` only allows you to either use the Options API or the Composition API.

**Comment by poacher2k** [comment]
@Haberkamp : We already reverted to `3.12.0`, and while the fixes you outline works, this `patch` commit was still a breaking change, so you might consider reverting this for `^3` regardless, as it might be broken for more people too.
